Repository BrainiacWizards/brainiacwiz, pull requests merged in 2024-06, with the labels that each got.

#60 update login UI and add more functionality on Host View and Looby
  .env
  .gitignore
  assets/css/host.css
  assets/css/style.css
  assets/icons/all.css
  assets/icons/all.min.css
  assets/icons/brands.css
  assets/icons/brands.min.css
  assets/icons/fontawesome.css
  assets/icons/fontawesome.min.css
  assets/icons/regular.css
  assets/icons/regular.min.css
  assets/icons/solid.css
  assets/icons/solid.min.css
  assets/icons/svg-with-js.css
  assets/icons/svg-with-js.min.css
  assets/icons/v4-font-face.css
  assets/icons/v4-font-face.min.css
  assets/icons/v4-shims.css
  assets/icons/v4-shims.min.css
  assets/icons/v5-font-face.css
  assets/icons/v5-font-face.min.css
  assets/js/host.js
  assets/js/looby.js
  assets/js/main.js
  assets/js/utils/nft.html
  assets/js/utils/nftgen.js
  fb_config.js
  package-lock.json
  package.json
  pages/auth/auth.html
  pages/auth/auth.js
  pages/auth/fb.js
  pages/auth/gamepin/gamepin.css
  pages/auth/gamepin/gamepin.js
  pages/auth/gamepin/index.html
  pages/auth/login.html
  pages/auth/styleAuth.css
  pages/play/host/host.html
  pages/play/lobby.html
  project-aim.txt
Labels: enhancement, feature release

#71 chore: Update help links in various pages
  index.html
  pages/Wallet profile/Profile.html
  pages/auth/auth.html
  pages/auth/gamepin/gamepinUI/index.html
  pages/auth/gamepin/index.html
  pages/auth/login.html
  pages/play/host/host.html
  pages/play/lobby.html
  pages/play/post-quiz.html
  pages/play/quiz.html
  pages/ranking.html
  pages/user/profile.html
Labels: enhancement, Review effort [1-5]: 2

#72 update mmpotulo branch from beta
  .vscode/settings.json
  assets/css/host.css
  assets/js/host.js
  assets/js/looby.js
  assets/js/main.js
  assets/js/profile.js
  assets/js/quiz.js
  assets/js/ranking.js
  assets/js/utils/metamask.js
  assets/js/utils/setnavbar.js
  index.html
  pages/Wallet profile/Profile.html
  pages/Wallet profile/ProfileMain.js
  pages/Wallet profile/ProfileStyle.css
  pages/auth/auth.html
  pages/auth/fb.js
  pages/auth/gamepin/gamepinUI/index.html
  pages/auth/gamepin/index.html
  pages/auth/login.html
  pages/play/host/host.html
  pages/play/host/transfer/indexMain.js
  pages/play/host/transfer/indexStyling.css
  pages/play/lobby.html
  pages/play/post-quiz.html
  pages/play/quiz.html
  pages/ranking.html
  pages/user/profile.html
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 4

#74 fix campaign and score board errors
  assets/js/host.js
  assets/js/postquiz.js
  assets/js/ranking.js
  pages/auth/fb.js
  pages/play/host/transfer/indexMain.js
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#75 Charles
  assets/css/user.css
  assets/js/profile.js
  pages/play/host/transfer/indexMain.js
  pages/user/profile.html
Labels: enhancement, Review effort [1-5]: 3

#76 chore: Update help links and help button icons
  index.html
  pages/Wallet profile/Profile.html
  pages/auth/auth.html
  pages/auth/gamepin/gamepinUI/index.html
  pages/auth/gamepin/index.html
  pages/play/post-quiz.html
  pages/play/quiz.html
  pages/ranking.html
  pages/user/profile.html
Labels: enhancement, Review effort [1-5]: 2

#77 bug fix from beta
  .vscode/settings.json
  assets/css/host.css
  assets/css/style.css
  assets/css/user.css
  assets/js/api/api.js
  assets/js/api/apiIMG.html
  assets/js/host.js
  assets/js/looby.js
  assets/js/postquiz.js
  assets/js/profile.js
  assets/js/quiz.js
  assets/js/ranking.js
  index.html
  pages/Wallet profile/Profile.html
  pages/Wallet profile/ProfileMain.js
  pages/Wallet profile/ProfileStyle.css
  pages/auth/auth.html
  pages/auth/fb.js
  pages/auth/gamepin/gamepinUI/index.html
  pages/auth/gamepin/index.html
  pages/auth/login.html
  pages/auth/styleAuth.css
  pages/play/host/HostDeposit/finalIndex.html
  pages/play/host/HostDeposit/indexMain.js
  pages/play/host/HostDeposit/indexStyling.css
  pages/play/host/host.html
  pages/play/host/transfer/indexStyling.css
  pages/play/lobby.html
  pages/play/post-quiz.html
  pages/play/quiz.html
  pages/ranking.html
  pages/user/profile.html
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 4

#78 Hope
  .vscode/settings.json
  assets/js/main.js
  assets/js/profile.js
  index.html
  pages/auth/fb.js
  pages/user/profile.html
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#79 Refactor `host.js` to fix dummy object not defined error
  assets/js/host.js
Labels: enhancement, Review effort [1-5]: 2, Bug fix
